export const PROFESSIONAL_LOGIN_REQ = 'PROFESSIONAL_LOGIN_REQ';
export const PROFESSIONAL_LOGIN_SUCCESS = 'PROFESSIONAL_LOGIN_SUCCESS';
export const PROFESSIONAL_LOGIN_FAIL = 'PROFESSIONAL_LOGIN_FAIL';
export const PROFESSIONAL_LOGOUT = 'PROFESSIONAL_LOGOUT';

export const PROFESSIONAL_REGISTER_REQ = 'PROFESSIONAL_REGISTER_REQ';
export const PROFESSIONAL_REGISTER_SUCCESS = 'PROFESSIONAL_REGISTER_SUCCESS';
export const PROFESSIONAL_REGISTER_FAIL = 'PROFESSIONAL_REGISTER_FAIL';

export const PROFESSIONAL_INFO_REQ = 'PROFESSIONAL_INFO_REQ';
export const PROFESSIONAL_INFO_SUCCESS = 'PROFESSIONAL_INFO_SUCCESS';
export const PROFESSIONAL_INFO_FAIL = 'PROFESSIONAL_INFO_FAIL';
